### ISSUE TITLE
No plugin found for prefix 'springboot-swagger-3' / Download of maven dependency 'springboot-swagger-3' requires authentication

### ISSUE THREAD

**Issue by krippendorf** [DP-3T/dp3t-sdk-backend#165]
Running **make** stops with a BUILD FAILURE due to non public maven dependency: 

`<groupId>ch.ubique.openapi</groupId>
<artifactId>springboot-swagger-3</artifactId>`

`Authentication failed for https://maven.pkg.github.com/Ubique-OSS/springboot-swagger3/org/codehaus/mojo/maven-metadata.xml 401 Unauthorized`

`[[ERROR] No plugin found for prefix 'springboot-swagger-3' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/devUser/.m2/repository), github (https://maven.pkg.github.com/Ubique-OSS/springboot-swagger3), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
`

**Comment by cpepi001** [comment]
Maybe the same error I had #92

**Comment by krippendorf** [comment]
@cpepi001 You're right -> I'll create a PR to mention that m2 setting in the README file, becaue recent versions of https://github.com/Ubique-OSS/springboot-swagger3 is not git tagged when doing a manual local install

**Comment by ubamrein** [comment]
Thanks for the PR. In order to let the SonarCloud Scans run, I merged in a local branch and made a new PR. That PR is now on develop!
