### ISSUE TITLE
Exposure Notification v1.5

### ISSUE THREAD

**Issue by jorgejams88** [DP-3T/dp3t-sdk-backend#180]
Hi everyone!!!

Thanks for your help, I've been using this implementation for some time now. Today I had a meeting with Google, and they told me that with the version 1.5 of the Exposure Notification API, there might be some crashes in the backend. I do not have details as to what those changes might be or the exact effect, but I thought you should also know.

**Comment by ineiti** [comment]
Is there an official changelog or API documentation for the 1.5 GAEN? Google search doesn't seem to know about it ;)

**Comment by ubamrein** [comment]
We are in contact with Google/Apple and are already planing fixes for certain problems arising due to the change of the API. Thanks for the notice anyways! 

I will reference this issue with fixes to be compatible with the version 1.5 of the API.

**Comment by ubamrein** [comment]
With the current Release Candidate [v1.1.0-RC1](https://github.com/DP-3T/dp3t-sdk-backend/releases/tag/v1.1.0-RC1), there  should not be any issues anymore. So I'll close this one.

For any concrete problems, please open a separate issue :)

**Comment by marado** [comment]
> Is there an official changelog or API documentation for the 1.5 GAEN? Google search doesn't seem to know about it ;)

https://developers.google.com/android/exposure-notifications/doc-change-log
