### ISSUE TITLE
Validate rolling period does not exceed 144 (1 day)

### ISSUE THREAD

**Issue by ubamrein** [DP-3T/dp3t-sdk-backend#214]
Currently we were only checking for lower bounds and adjusting accordingly. With the API changes of 1.6, we have to ensure that the rolling period does not exceed 144.

**Comment by marado** [comment]
We have been seeing references to an 1.6 version of the API, but on the official website (or where I understand should we find information about it, https://developers.google.com/android/exposure-notifications/exposure-notifications-api ) there are only references for 1.5 yet.

Where are those "API changes of 1.6" described?

**Comment by ineiti** [comment]
@marado if you search for `1.6` in the link you sent, you'll find multiple references saying things like _getDailySummaries() (available starting in v1.6)_ - not sure whether it was already available when you wrote your comment, though ;)

**Comment by marado** [comment]
Thanks, the release notes seem to be here: https://developers.google.com/android/exposure-notifications/release-notes#v16_august_2020

**Comment by martinalig** [comment]
fixed in release 2.0.0
