### ISSUE TITLE
upload api is missing in swagger dp3t-sdk-backend

### ISSUE THREAD

**Issue by vijayakumarmariyappan** [DP-3T/dp3t-sdk-backend#216]
@ubamrein 

We have analysed further about DP3T and contact tracing system.

Based on this swagger
https://editor.swagger.io/?url=https://raw.githubusercontent.com/DP-3T/dp3t-sdk-backend/develop/documentation/yaml/sdk.yaml

**What we are trying to acheive?:**
We are building iOS and Android App for the internal purpose of the company, not for the public. So it will help our employee to be safe in the building. All employees would install our iOS or Android App in their mobile.

1. For that we have integrated your iOS(dp3t-sdk-ios) & Android SDK(dp3t-sdk-android) into our app. 
2. have deployed your dp3t-sdk-backend (https://github.com/DP-3T/dp3t-sdk-backend) server in the cloud.

**Doubts:**
In the shared [dp3t-app-ios-demo](https://github.com/DP-3T/dp3t-app-ios-demo/blob/develop/DP3TApp/Screens/Debugscreen/NSDebugDatabaseUploadHelper.swift) project we are seeing the API (https://dp3tdemoupload.azurewebsites.net/upload) that uploads the SQLite DB to the server. But in the above swagger documentation we don't have that API. is that "upload" API implemented in your dp3t-sdk-backend?

Can we set the secret key(email id or unique id to employee permanently), while initializing your iOS / Android SDK in the user's device? 

Thank you for your help!

**Comment by ubamrein** [comment]
This screen is only for debugging purposes. You should not use it in production.

Further, the API is not part of the Swagger file, as it is a [Azure-Blobstorage](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction). As such Microsoft provides its own SDK and Documentation.

A remark in general: The whole idea of the DP3T and exposure notification project is to have a privacy conserving technology, which still allows for tracing. If it is your intention, to collect more data than necessary then you should consider using something else. 

Please be also assured that according to [Exposure Notification Addendum](https://developer.apple.com/contact/request/download/Exposure_Notification_Addendum.pdf) you can only use the API if you are providing an official app for a health authority.
