### ISSUE TITLE
Remove DPPPT services

### ISSUE THREAD

**Issue by ineiti** [DP-3T/dp3t-sdk-backend#228]
🔑
Currently the backend still contains the dpppt backend, which has been replaced by the GAEN backend.
I propose to remove all code references to the DPPPT backend.
This reduces bit-rotting, old tests that don't work anymore, and keeps the code cleaner.

**Comment by marado** [comment]
Currently, this DP3T SDK implementation can both be used with or without GAEN, and has been considered the de facto reference implementation of DP3T.

Removing the "dp3t" from "dp3t-sdk-backend", turning it into a de facto "gaen-backend" seems to ruin its purpose.

**Comment by ineiti** [comment]
Interesting - I was not aware that there are DPPPT clients out there who are still using these endpoints. If it's actively used, then we need to make sure that it's still available, and that the tests continue to be working...

Let's see what the Ubique team thinks.

**Comment by ineiti** [comment]
As the code will still be available in the previous versions, and as nobody seems to actually use it, I think it's better if we remove it here. If there are people actually using this code, please speak up, else it will be removed.

**Comment by ineiti** [comment]
We decided to do:
- tag the latest commit that still includes DPPPT
- merge #231 

So if anybody _does_ use the pre-GAEN API, she still can get the code.
