### ISSUE TITLE
Different insertmanager for exposed and exposed next day

### ISSUE THREAD

**Issue by martinalig** [DP-3T/dp3t-sdk-backend#240]
To make the insert process more clear, there should be an insertmanager for the exposed endpoint and one insertmanager for the exposed next day endpoint. 

This will also make the EnforceMatchingJWTClaims filter more understandable and less error prone.

**Comment by ineiti** [comment]
Should this be resolved before #213 goes in?

**Comment by martinalig** [comment]
Yes, this should go in before, as it is a refinement of the insert manager.
