### ISSUE TITLE
Fix logger warnlevel when normalizing request time

### ISSUE THREAD

**Issue by martinalig** [DP-3T/dp3t-sdk-backend#269]
Currently, there is an ERROR logged when the request time exceeds the configured normalized request time in the GaenController  exposed and exposedNextDay requests.

This is clearly not an error, so the level should be adjustet to WARN. Also some more information could be printet out, how much too long the request ist actually going.

**Comment by ineiti** [comment]
This _is_ an error, and is there explicitly to be an error! If the request exceeds the normalized request time, then the normalized request time needs to be increased, else an attacker could learn something about the state of the database.

So the correct solution for this error is to increase the normalized request time.

**Comment by ineiti** [comment]
See #270

**Comment by martinalig** [comment]
Closed, as already explained by @ineiti 
This is an error as this actually breaks the system from a privacy perspective.
