### ISSUE TITLE
Tag v2.0.0 doesn't pass tests

### ISSUE THREAD

**Issue by iCesofT** [DP-3T/dp3t-sdk-backend#271]
Hi,

If I download the .tar.gz from https://github.com/DP-3T/dp3t-sdk-backend/releases/tag/v2.0.0:

1.  I have to init git because the plugin `git-commit-id-maven-plugin`. You should add:
```
<failOnNoGitDirectory>false</failOnNoGitDirectory>
```
2. If I try to package (`make package` o `mvn clean package`), I get these results:
```
[ERROR] Failures:
[ERROR]   GaenDataServiceTest.upsert:71 expected: <2> but was: <0>
[ERROR]   PostgresGaenDataServiceTest.upsert:186 expected:<1> but was:<0>
```

**Comment by iCesofT** [comment]
Maybe depends on time execution those tests work? I run again right now and I worked :?

**Comment by ineiti** [comment]
That's very interesting. We had some tests that didn't run because it used the local time to calculate some boundaries, and it failed either in the afternoon, or close to midnight. Might be something similar here. I'll have a look at it later this afternoon.

**Comment by martinalig** [comment]
I will close this issue for now, as v2.1.0 and v2.2.0 have been released.
