### ISSUE TITLE
Deprecate spring-boot-starter-cloud-connectors in favour of Java CFEnv

### ISSUE THREAD

**Issue by iCesofT** [DP-3T/dp3t-sdk-backend#272]
On your code, you are using this dependency
https://github.com/DP-3T/dp3t-sdk-backend/blob/288d099b9ed3e752c382a273289668a466fe5aeb/dpppt-backend-sdk/dpppt-backend-sdk-ws/pom.xml#L35

```xml
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-cloud-connectors</artifactId>
		</dependency>
```
(and the code that uses it: https://github.com/DP-3T/dp3t-sdk-backend/blob/develop/dpppt-backend-sdk/dpppt-backend-sdk-ws/src/main/java/org/dpppt/backend/sdk/ws/config/WSCloudBaseConfig.java)

But as you can see, it is deprecated (https://github.com/spring-projects/spring-boot/issues/17877), and you are not able to upgrade to Spring Boot 2.3.X because of this.

**Comment by martinalig** [comment]
Thanks for the input. We will adapt this as soon as we go to 2.3.x.

**Comment by iCesofT** [comment]
We (Spain) are going to migrate to 2.3.5 but we don't need that library. Are cloud specific libraries necessary for you?

**Comment by martinalig** [comment]
Yes, the cloud libraries are needed for us as we deploy on Cloudfoundry.

Anyway, we take this into the next release 2.0.2.

**Comment by martinalig** [comment]
See https://github.com/DP-3T/dp3t-sdk-backend/pull/280
