### ISSUE TITLE
Releases vs Maven version

### ISSUE THREAD

**Issue by iCesofT** [DP-3T/dp3t-sdk-backend#275]
It is not a real bug but a release convention. You have [23 releases](https://github.com/DP-3T/dp3t-sdk-backend/releases) but your Maven projects are still on "1.0.0-SNAPSHOT".

The latest release is "2.0.0" so master branch should have 2.0.0 in Maven and develop branch should have 2.0.0-SNAPSHOT or 2.0.1-SNAPSHOT.

https://github.com/DP-3T/dp3t-sdk-backend/blob/288d099b9ed3e752c382a273289668a466fe5aeb/dpppt-backend-sdk/pom.xml#L20

**Comment by martinalig** [comment]
See https://github.com/DP-3T/dp3t-sdk-backend/pull/280
