### ISSUE TITLE
Tag name clashed with brach develop

### ISSUE THREAD

**Issue by slyfer** [DP-3T/dp3t-sdk-backend#30]
Hi, after last git pull upstream develop I was unable to do git push origin with error: 
error: dst refspec refs/heads/develop matches more than one.

I see that there is a tag named "refs/heads/develop". Can you please remove it? Seems an error

**Comment by martinalig** [comment]
Hi
Does not seem to be an issue here. Have you tried to make a fresh clone? Or you might have a wrong origin?

**Comment by slyfer** [comment]
Yes I have made a fresh clone more than once.

Here there is a more details about the problem:

https://markhneedham.com/blog/2013/06/13/git-having-a-branchtag-with-the-same-name-error-dst-refspec-matches-more-than-one/

**Comment by ubamrein** [comment]
Oke sorry for that, the tag was pushed by a github action. We now deleted the tag and fiixed the github action. So if you do a fresh clone it should work again
