### ISSUE TITLE
Use Spring Data JPA.

### ISSUE THREAD

**Issue by antrix190** [DP-3T/dp3t-sdk-backend#305]
While going through the code, I could notice high level of verbosity. Hence was wondering if it's a good idea to replace `org.springframework.jdbc.core` with [Spring Data JPA](https://spring.io/projects/spring-data-jpa)

[Reference](https://github.com/DP-3T/dp3t-sdk-backend/blob/33586ca38ef2b5706dd6a04b1687ebebbc617f35/dpppt-backend-sdk/dpppt-backend-sdk-data/src/main/java/org/dpppt/backend/sdk/data/gaen/DebugJdbcGaenDataServiceImpl.java#L45)

**Comment by martinalig** [comment]
Hi, 

Thanks for the input. 

We do not plan to replace JDBC with JPA. 

Best regards
