### ISSUE TITLE
v0.1

### ISSUE THREAD

**Issue by zerjioang** [DP-3T/dp3t-sdk-backend#38]
Hi,

I checkout your project and found some errors while trying to follow your readme instructions to deploy the ws. I was wondering what are the required efforts to have a initial v.01 MVP backend implementation so that we, developers and researcher, can start collaborating to dp3t.

**Comment by martinalig** [comment]
Hi, thanks for the input, there was a lot of development going on this week, we will try to update the documentation as soon as possible.
