### ISSUE TITLE
Consider to migrate to java 11

### ISSUE THREAD

**Issue by slyfer** [DP-3T/dp3t-sdk-backend#41]
Have you consider to migrate to java 11?

**Comment by jeffallen** [comment]
That would seem to be a distraction at a critical time for a very tight schedule. Can you explain what it would improve? What are the costs of the change?

**Comment by slyfer** [comment]
Hi Jeff, in no specific order the most relevant changes (for me):

-  java 8 will not receive more updates -> https://www.oracle.com/java/technologies/java-se-support-roadmap.html
- java 11 has parallel G1 garabage collector that improves performance
- from java 10 the jvm is Container Aware
- Security improvements: TLS 1.3: Now TLS 1.3 implemented in JDK.

The costs to change is near to 0, all testa passes using java 11, but the test not covers all the production code (this is not only a problem for migration to java 11)

**Comment by jeffallen** [comment]
Thanks for educating me!
