### ISSUE TITLE
API Roadmap

### ISSUE THREAD

**Issue by tillmzw** [DP-3T/dp3t-sdk-backend#42]
Hey all,

we are currently trying to follow along with implementations of the DP3T specification and realized today that the newest version of the Android SDK "doesn't work" anymore, we think because the communication channel is broken with the backend (which we implemented following . While searching for causes I found that the SDK seems to have removed support for JSON and instead implemented protobuf, which is supported by pull requests #29 & #28 on the backend site.

My actual question: Do you have a roadmap for features like this so we don't run behind with backend features (or any component for that matter)? Specifically with regards to breaking changes like this seems to be, which makes upgrading and integrating new features a hassle on related systems.

Thanks for your efforts!

**Comment by ubamrein** [comment]
Hey there!

Sorry for that! Currently we are very much under pressure to have something ready. Hence, the speed at which we make iterations is incredibly fast and we really lack behind documentation.

As soon as we have released a first stable version, which is to be expected within the next weeks, we will focus on roadmaps and future improvements as well as on working better with Github Releases and such.

On the backend side we still support JSON and we also plan to continue such a support. As such I would rather open an issue on the client SDKs.

**Comment by tillmzw** [comment]
Thanks for the reply. I understand that you're under time pressure. It makes it nigh impossible however for keep a separate implementation of the backend in sync with your progress. Here's hope that our implementations do not diverge too much.

Do you think that you would profit in some way or another from our implementation of a backend, given that we're always lagging behind a few steps?
