### ISSUE TITLE
Backend should support eventual coexistence of DP3T with Google/Apple's protocol

### ISSUE THREAD

**Issue by jorgejams88** [DP-3T/dp3t-sdk-backend#44]
Maybe the database schema could have another field specifying the protocol that was used, so that apps after receiving the data could know which validation algorithm to run in order to verify if they have been in contact with an infected person.

**Comment by ryanbnl** [comment]
I'm not sure how a DP3T installation can work without using the Google/Apple APIs on the phones. The new A/G specifications are pretty much identical to option 1 of the DP3T specs as far as I can see.

The APIs don't expose the local database of the chirps / empID / Rolling Proximity Identifier that have been stored on the device unless they test positive as far as I can see.

**Comment by jorgejams88** [comment]
> I'm not sure how a DP3T installation can work without using the Google/Apple APIs on the phones. The new A/G specifications are pretty much identical to option 1 of the DP3T specs as far as I can see.
> 
> The APIs don't expose the local database of the chirps / empID / Rolling Proximity Identifier that have been stored on the device unless they test positive as far as I can see.

The description of the Android SDK says:

> Our immediate roadmap is: to support the Apple/Google wire protocol, to be forward-compatible, and to support the actual Apple/Google API as soon as it is released to iOS and Android devices.

When this happens and there are already people using DP3T, it may be possible for a transition time in which some users are already exchanging Google/Apple protocol compliant ephIds, but need to validate an id of a user that happened during a time when they still had the previous protocol. 

By adding an identifier of the type of ephid to the backend table, when the user downloads it, they could also know which protocol to use when validating an ephId of an infected person

**Comment by martinalig** [comment]
Thanks for the inputs. As soon as more information about A/G is availble, support and migration will also be added to the backend.
