### ISSUE TITLE
Consider migration from JodaTime to java.time (JSR-310)

### ISSUE THREAD

**Issue by slyfer** [DP-3T/dp3t-sdk-backend#45]
After the release of Java 8, authors consider the project to be mostly finished and advise to use the Java 8 API if possible.

Extract from https://www.joda.org/joda-time/
"Note that from Java SE 8 onwards, users are asked to migrate to java.time (JSR-310) - a core part of the JDK which replaces this project."

**Comment by jeffallen** [comment]
I made a quick try at this last night, but it seemed to be harder than I expected brcause their apis are quite different. Can you recommend any good conversion tools or recipe websites?

**Comment by slyfer** [comment]
This is a good start point: https://blog.joda.org/2014/11/converting-from-joda-time-to-javatime.html

If you want I can do a PR

**Comment by jeffallen** [comment]
I am not on the core team, so the result of this issues does not depend on input from me.

**Comment by giacgbj** [comment]
Pay attention to this [nasty bug](https://bugs.openjdk.java.net/browse/JDK-8222187) if you use the "wrap" methods.

**Comment by ubamrein** [comment]
Thanks for the suggestion. Since we used jodatime for many projects in the past, we felt comfortable with it and just continued to use it.

But we try to refactor and document this week, and with this refactoring we are switching from jodatime to java8 api. So stay tuned :)

**Comment by bachmann-ubique** [comment]
fixed
