### ISSUE TITLE
JWT onset date should be used for validation, but not override the key date

### ISSUE THREAD

**Issue by AndreasHuber-CH** [DP-3T/dp3t-sdk-backend#52]
When uploading a key, the server receives two dates: The client provides a key with the associated keyDate, and the JWT contains the onset date of this patient as determined by some medical institute.
The following code combines the two dates in a way I'm not sure is correct:
https://github.com/DP-3T/dp3t-sdk-backend/blob/c4638064e54fc54185f7d213a132ced8d29c29f0/dpppt-backend-sdk/dpppt-backend-sdk-ws/src/main/java/org/dpppt/backend/sdk/ws/security/JWTValidateRequest.java#L31-L47

There are three different use cases:
- keyDate == jwt.onset: This should be the normal use case where the patient provided the appropriate key for the onset date that was determined by the health institute
- keyDate > jwt.onset: This can happen when the client does not have the key of the onset date and decides to upload a newer key instead (e.g. the app was not yet installed at onset date)
- keyDate < jwt.onset: The client uploaded a key that is older than onset date. This should not happen, but the current implementation accepts this while replacing the keyDate with the onset date. But this means a client could publish his key from "Monday" with an onset date of "Wednesday", and DP-3T will store and communicate to clients that this key is from "Wednesday". I didn't check client implementation yet to see how much effect this wrong information would have on the client.

To me the correct implementation should look like this:
- The client must provide the correct keyDate for its key.
- The server should validate keyDate >= jwt.onset, and reject the request otherwise (but not modify the keyDate).
- Similarly, the server should also reject the request if keyDate > today() (and not accept it while replacing the keyDate with today() like is done now)

If you agree I can work on a fix

**Comment by ubamrein** [comment]
Thanks for your bug report! We really missed that one. 

It should be fixed by now. We would be glad, if you could double check shortly.

**Comment by AndreasHuber-CH** [comment]
The fix looks good to me. You handled even one more case, refusing the upload of old data.
