### ISSUE TITLE
Use jib to let maven build docker images

### ISSUE THREAD

**Issue by DavyLandman** [DP-3T/dp3t-sdk-backend#6]
Hi There,

you can simplify the build of the docker container by using [GoogleContainerTools/jib](https://github.com/GoogleContainerTools/jib), it includes a [maven plugin](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin) that works without have a local docker install, great for CI environments that might already be running inside docker.

If you want, I could help set it up, but only if you think it's useful to have.

Cheers,
Davy

**Comment by ubamrein** [comment]
Hey thanks for the tip! 

I'm currently not sure how useful it will be, since Github already has actions to build and push docker images (as other CIs do as well).

Do you see any advantages of using jib vs. Github actions/Jenkins Pipeline/...?

**Comment by DavyLandman** [comment]
Sorry, I'll try to elaborate. Jib is a plugin that lets maven (as part of the build process) also generate docker images.  One of the advantages is that you do not need to maintain a Dockerfile, it infers it from the context (and from the pom.xml file).

Next to this you could use jib to push to dockerhub or something else, or you could use the client specific to Github Actions/Jenkins to handle that.

So, your CI script would be simpler and it's easy for users to locally build a docker image (like a tar that they can share with you for testing), even when they don't have docker installed locally.

**Comment by ubamrein** [comment]
I see! Thanks for elaborating!

So if you're still interested, we would be glad, if you could set it up and make a pull request :)

**Comment by DavyLandman** [comment]
Ok, I'll try to create a pull request somewhere the coming 2 days.
