### ISSUE TITLE
API alignment with dp3t-app-ios

### ISSUE THREAD

**Issue by DuffMck** [DP-3T/dp3t-sdk-backend#63]
Hi,

we are developing on your project **dp3t-app-ios** but the code need some APIs that are not exposed by the actual version of backend project. The first two APIs that we have discovered are
- http://63.35.195.11:8080/v1/config
- http://63.35.195.11:8080/v1/register

Are we doing something wrong or is it normal?

Thanks!

**Comment by jorgejams88** [comment]
I had the same problem, those two endpoints are not actually used, in fact the Android app does not even reference them.

The easiest way to get this running is to roll your own instance of the backend and change the app to use that baseURL.

**Comment by ubamrein** [comment]
The `register` request should not be used anymore. The `config` request in a different repository.

See this [Issue](https://github.com/DP-3T/dp3t-sdk-backend/issues/76) for links to the respective repositories.
