### ISSUE TITLE
production backend configuration

### ISSUE THREAD

**Issue by zerjioang** [DP-3T/dp3t-sdk-backend#68]
after having the latest version of the backend up and running and once connected to our pgsql database, im wondering what could be the roadmap for starting to test the tech with small group of people. I know current development is in a rush, and you guys commit a lot of changes in near no time, but I would like to know if you have thought about

having a kind of metrics system minimal dashboard integrated with springboot backend for getting some feedback of the server. Metrics such following seems quite interesting for us:

* number of total connections per day
* active connections
* dropped connections
* invalid auth attemps
* number of buckets request
* number of failed bucket request
* etc

As you can see, metrics are not user centric so they are totally privacy preserving and they focus on getting data from server work status and its workload.

If you never plan to have such information on the server side, i would like to know if I make a fork of current repository, will you be planning to release breaking changes of core functions soon? or everything will remain pretty much the same?

**Comment by ubamrein** [comment]
Most of it is already included in springboot using actuators. You can then use Prometheus scraping with e.g. a Grafana Dashboard to get a lot of default metrics for the web service. 
 
- [Actuators](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html)
- [Prometheus](https://prometheus.io/)
- [Grafana](https://grafana.com/)
