### ISSUE TITLE
Code quality checks

### ISSUE THREAD

**Issue by wmeints** [DP-3T/dp3t-sdk-backend#7]
Love the idea of using open source to implement contact tracing. But as a developer I feel a little bit hurt. I'm missing some stuff around code quality:

* Dependency checks to find security leaks in libraries used by the SDK.
* Code style checks to ensure code is readable and maintainable.
* Unit-tests to validate that the code works as expected.
* Contributor guide, how can I add to this, or fix bugs?

I hope you're going to add these to the code base.

**Comment by ubamrein** [comment]
Thanks for your feedback! We are currently working on various tests and analysis methods (as e.g. also include some static analysis) and contributor guide lines.

Regarding the dependency checks, we were relaying on Github to check for security vulnerabilities.
