### ISSUE TITLE
Store coarse timestamps to increase privacy

### ISSUE THREAD

**Issue by AndreasHuber-CH** [DP-3T/dp3t-sdk-backend#72]
You've added the ability that clients can perform fake upload requests to the backend. This makes it impossible to find the IPs of infected users that upload their keys through network traffic observation or from an access log on the server, as infected users uploading their keys and non-infected users performing fake uploads leave the same traces.

But if an attacker would gain access to the database on the server this no longer holds true, because the database contains precise "received_at" timestamps that would allow separating the real uploads from the fake ones.

As "received_at" timestamps are present in the "t_exposed" and the "t_redeem_uuid" table, it would also be possible to figure out which JWT was used to upload which key. Issue DP-3T/documents#206 goes in that direction. Although there would be another indirection to get from the JWT to the patient, as the health authority hands out an authorisation code, that is then exchanged by the app for a JWT through the authorisation server before submitting it to the backend.

I think the risk of someone hacking the server database and analysing network traffic is probably not huge; and I don't see any reason why health authorities would invest energy in trying to track the keys uploaded by their patients. But I think both issues could be mitigated relatively easily by storing only coarse timestamps in the "received_at" columns of both tables.

Instead of storing the current timestamps with millisecond precision, the timestamps could be rounded down to the start of the current bucket without changing the functionality of the server - the server would store only as much information as needed to function properly.

**Comment by AndreasHuber-CH** [comment]
Actually, for the t_redeem_uuid table, you could either clean up the table much sooner as token expire pretty quickly (e.g. after ${ws.app.jwt.maxValidityMinutes: 60} that has been added in https://github.com/DP-3T/dp3t-sdk-backend/pull/78) - or you could change the DB model to store the expiration of the token instead of the received_at and during cleanup delete all IDs of expired tokens.

**Comment by martinalig** [comment]
Fixed by #152.
