### ISSUE TITLE
Is the generation of access tokens part of the scope of this sdk?

### ISSUE THREAD

**Issue by jorgejams88** [DP-3T/dp3t-sdk-backend#76]
New Android and iOS apps were released, and Android specifically has two endpoints that are not present in this version of the backend sdk:

/v1/config (this one is defined in [this](https://github.com/DP-3T/dp3t-config-backend-wip) repo)
/v1/onset (to validate access tokens)

Is access token validation part of the scope?

**Comment by luc-devallonne-nagra** [comment]
You may want to look into [this ](https://github.com/admin-ch/CovidCode-Service) which provides an implementation of the /v1/onset endppoint

**Comment by martinalig** [comment]
The config endpoint is not part of the SDK. It contains app-specific parameters and functions. A current implementation which is used by the iOS and Android apps is in this repo: https://github.com/DP-3T/dp3t-config-backend-wip
