### ISSUE TITLE
Fix JWT expiration validation

### ISSUE THREAD

**Issue by AndreasHuber-CH** [DP-3T/dp3t-sdk-backend#77]
The backend accepts JWT that have no expiration date or an expiration date far in the future.
The JWT ID is stored for a configurable number of days to prevent re-use of the same token (21 by default).
So if a JWT would exist that is valid for a long time, it could be reused every 21 days.
While I assume that the authorization server never produces such JWT, the backend should do its own validation and reject such JWTs.

This check must be skipped for the "fake" JWT as they actually have no expiration date (as I can see in https://github.com/admin-ch/CovidCode-Service)

**Comment by ubamrein** [comment]
Thanks for your contribution!
