### ISSUE TITLE
Apple's potential role wrt Diagnosis Servers

### ISSUE THREAD

**Issue by ralfr** [DP-3T/dp3t-sdk-backend#8]
First things first: I salut everyone in DP-3T for not giving up on the *decentralized* aspects of pppt.

I don’t have any remarks on the actual code or implementation, yet, but would love to get your feedback on a concept / suggestion I’ve suggested in the linked article.

Not sure whether this is a good place to ask but since I’m not aware of any discussion forum for DP-3T I thought I’d post it here.

https://corona-app.watch/2020/04/18/apple-please-continue-to-enforce-decentralization-in-contact-tracing/

**Comment by ralfr** [comment]
The biggest advantage of this would be that at no time the app would see *any* of the IDs.

**Comment by martinalig** [comment]
Hi
Thanks for your input. For comments about the system please see https://github.com/DP-3T/documents
