### ISSUE TITLE
Certain identifiers in payload don't change

### ISSUE THREAD

**Issue by romeokienzler** [DP-3T/dp3t-sdk-backend#81]
Please see attached screenshots for a BLE scanner, 
<img width="375" alt="signal-2020-05-05-163059" src="https://user-images.githubusercontent.com/5694071/81148611-e8a3ff80-8f7c-11ea-9018-415feaeeefa2.png">
<img width="375" alt="signal-2020-05-05-222024" src="https://user-images.githubusercontent.com/5694071/81148629-efcb0d80-8f7c-11ea-86f2-326e640f5416.png">

You can see at the bottom, the Service UUIDs field and also the 2nd "Custom Service" has an ID which was not changing after one day

**Comment by ubamrein** [comment]
The service UUID is not supposed to change. This identifier is needed such that the apps can identify the correct BLE packages. This UUID is the same for everyone using the app.

The important part is that the ephemeral ID changes, which should be the last 16 bytes of the advertisement data.

Anyways, the backend sdk is not responsible for any bluetooth communication. So if you have further questions or issues, please raise them in the appropriate locations.

[Here](https://devzone.nordicsemi.com/nordic/short-range-guides/b/bluetooth-low-energy/posts/ble-services-a-beginners-tutorial) you find some more information on bluetooth UUIDs, GATT characteristics and so on.

[iOS SDK](https://github.com/DP-3T/dp3t-sdk-ios)
[Android SDK](https://github.com/DP-3T/dp3t-sdk-android)

**Comment by romeokienzler** [comment]
@ubamrein thanks so much for your fast reply! thanks a lot!

**Comment by romeokienzler** [comment]
@ubamrein do you have an explaination why the custom service ID of the 2nd entry also still remains the same? Is it the same for all apps as well?

**Comment by ubamrein** [comment]
I'm not sure I understand what you are asking.

As far as I understand your screenshot correctly, you see the advertisement data, which includes the service UUID. Further down there is just a list of services found for the same broadcast address. So it makes sense that the service, which is identified via the service UUID is listed as well. If you compare the identifiers in the advertisement data and the one listed under services you see that they are  the same.

**Comment by romeokienzler** [comment]
@ubamrein so true sorry didn't see this. awesome! so I think this can be considered safe. thanks a ton for tour great work!
